config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'tasks', to: 'tasks#index'
  get 'tasks/new', to: 'tasks#new', as: :new_task
  post 'tasks', to: 'tasks#create'
  get 'tasks/:id', to: 'tasks#show', as: :task
  get 'tasks/:id/edit', to: 'tasks#edit', as: :edit_task
  patch "tasks/:id", to: "tasks#update"
  delete "tasks/:id", to: 'tasks#destroy', as: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def new
    @new_task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save
    redirect_to tasks_path
  end

  def edit
    @task_edit = Task.find(params[:id])
  end

  def update
    @task_updated = Task.find(params[:id])
    @task_updated.update(task_params)

    redirect_to task_path(@task_updated)
  end

  def show
    @task = Task.find(params[:id])
  end

  def destroy
    @task_destroy = Task.find(params[:id])
    @task_destroy.destroy

    redirect_to tasks_path
  end

  private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<%= simple_form_for(@task_edit) do |f| %>
  <%= f.input :title %>
  <%= f.input :details %>
  <%= f.input :completed %>
  <%= f.submit %>
<% end %>

app/views/tasks/index.html.erb
<h1>List of all task </h1>
<%= link_to "create a new task", new_task_path %>
<ol>
  <%@tasks.each do |task| %>
  <% if task.completed %>
    <li><i class="far fa-check-square"></i><%= link_to task.title, task_path(task) %></li>
  <% else %>
    <li><i class="far fa-square"></i><%= link_to task.title, task_path(task) %></li>
  <% end %>
  <% end %>
</ol>

app/views/tasks/new.html.erb
<%= simple_form_for(@new_task) do |f| %>
  <%= f.input :title %>
  <%= f.input :details %>
  <%= f.input :completed %>
  <%= f.submit %>
<% end %>

app/views/tasks/show.html.erb
<H1><%=@task.title %></H1>
<p><%= @task.details%></p>
<p><%= link_to "Back to the list", tasks_path %></p>
<p> <%= link_to "Edit", edit_task_path %> </p>
<p> <%= link_to "Destroy", destroy_path, method: :delete, data: {confirm: "are you sure?"} %> </p>